server:
  port: ${PORT:8080}

spring:
  application:
    name: clinica
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/haistech}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672/}
